// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models.WindowsUpdates {
    public enum DeploymentStateValue {
        [EnumMember(Value = "scheduled")]
        Scheduled,
        [EnumMember(Value = "offering")]
        Offering,
        [EnumMember(Value = "paused")]
        Paused,
        [EnumMember(Value = "faulted")]
        Faulted,
        [EnumMember(Value = "archived")]
        Archived,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
