// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models.WindowsUpdates {
    public enum UpdateCategory {
        [EnumMember(Value = "feature")]
        Feature,
        [EnumMember(Value = "quality")]
        Quality,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
        [EnumMember(Value = "driver")]
        Driver,
    }
}
