// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Me.Contacts
{
    /// <summary>Provides operations to manage the contacts property of the microsoft.graph.user entity.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetOrderbyQueryParameterType
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "id desc")]
        #pragma warning disable CS1591
        IdDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "categories")]
        #pragma warning disable CS1591
        Categories,
        #pragma warning restore CS1591
        [EnumMember(Value = "categories desc")]
        #pragma warning disable CS1591
        CategoriesDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "changeKey")]
        #pragma warning disable CS1591
        ChangeKey,
        #pragma warning restore CS1591
        [EnumMember(Value = "changeKey desc")]
        #pragma warning disable CS1591
        ChangeKeyDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "createdDateTime")]
        #pragma warning disable CS1591
        CreatedDateTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "createdDateTime desc")]
        #pragma warning disable CS1591
        CreatedDateTimeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "lastModifiedDateTime")]
        #pragma warning disable CS1591
        LastModifiedDateTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "lastModifiedDateTime desc")]
        #pragma warning disable CS1591
        LastModifiedDateTimeDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "assistantName")]
        #pragma warning disable CS1591
        AssistantName,
        #pragma warning restore CS1591
        [EnumMember(Value = "assistantName desc")]
        #pragma warning disable CS1591
        AssistantNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "birthday")]
        #pragma warning disable CS1591
        Birthday,
        #pragma warning restore CS1591
        [EnumMember(Value = "birthday desc")]
        #pragma warning disable CS1591
        BirthdayDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "children")]
        #pragma warning disable CS1591
        Children,
        #pragma warning restore CS1591
        [EnumMember(Value = "children desc")]
        #pragma warning disable CS1591
        ChildrenDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "companyName")]
        #pragma warning disable CS1591
        CompanyName,
        #pragma warning restore CS1591
        [EnumMember(Value = "companyName desc")]
        #pragma warning disable CS1591
        CompanyNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "department")]
        #pragma warning disable CS1591
        Department,
        #pragma warning restore CS1591
        [EnumMember(Value = "department desc")]
        #pragma warning disable CS1591
        DepartmentDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "displayName")]
        #pragma warning disable CS1591
        DisplayName,
        #pragma warning restore CS1591
        [EnumMember(Value = "displayName desc")]
        #pragma warning disable CS1591
        DisplayNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "emailAddresses")]
        #pragma warning disable CS1591
        EmailAddresses,
        #pragma warning restore CS1591
        [EnumMember(Value = "emailAddresses desc")]
        #pragma warning disable CS1591
        EmailAddressesDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "fileAs")]
        #pragma warning disable CS1591
        FileAs,
        #pragma warning restore CS1591
        [EnumMember(Value = "fileAs desc")]
        #pragma warning disable CS1591
        FileAsDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "flag")]
        #pragma warning disable CS1591
        Flag,
        #pragma warning restore CS1591
        [EnumMember(Value = "flag desc")]
        #pragma warning disable CS1591
        FlagDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "gender")]
        #pragma warning disable CS1591
        Gender,
        #pragma warning restore CS1591
        [EnumMember(Value = "gender desc")]
        #pragma warning disable CS1591
        GenderDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "generation")]
        #pragma warning disable CS1591
        Generation,
        #pragma warning restore CS1591
        [EnumMember(Value = "generation desc")]
        #pragma warning disable CS1591
        GenerationDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "givenName")]
        #pragma warning disable CS1591
        GivenName,
        #pragma warning restore CS1591
        [EnumMember(Value = "givenName desc")]
        #pragma warning disable CS1591
        GivenNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "imAddresses")]
        #pragma warning disable CS1591
        ImAddresses,
        #pragma warning restore CS1591
        [EnumMember(Value = "imAddresses desc")]
        #pragma warning disable CS1591
        ImAddressesDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "initials")]
        #pragma warning disable CS1591
        Initials,
        #pragma warning restore CS1591
        [EnumMember(Value = "initials desc")]
        #pragma warning disable CS1591
        InitialsDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "isFavorite")]
        #pragma warning disable CS1591
        IsFavorite,
        #pragma warning restore CS1591
        [EnumMember(Value = "isFavorite desc")]
        #pragma warning disable CS1591
        IsFavoriteDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "jobTitle")]
        #pragma warning disable CS1591
        JobTitle,
        #pragma warning restore CS1591
        [EnumMember(Value = "jobTitle desc")]
        #pragma warning disable CS1591
        JobTitleDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "manager")]
        #pragma warning disable CS1591
        Manager,
        #pragma warning restore CS1591
        [EnumMember(Value = "manager desc")]
        #pragma warning disable CS1591
        ManagerDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "middleName")]
        #pragma warning disable CS1591
        MiddleName,
        #pragma warning restore CS1591
        [EnumMember(Value = "middleName desc")]
        #pragma warning disable CS1591
        MiddleNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "nickName")]
        #pragma warning disable CS1591
        NickName,
        #pragma warning restore CS1591
        [EnumMember(Value = "nickName desc")]
        #pragma warning disable CS1591
        NickNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "officeLocation")]
        #pragma warning disable CS1591
        OfficeLocation,
        #pragma warning restore CS1591
        [EnumMember(Value = "officeLocation desc")]
        #pragma warning disable CS1591
        OfficeLocationDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "parentFolderId")]
        #pragma warning disable CS1591
        ParentFolderId,
        #pragma warning restore CS1591
        [EnumMember(Value = "parentFolderId desc")]
        #pragma warning disable CS1591
        ParentFolderIdDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "personalNotes")]
        #pragma warning disable CS1591
        PersonalNotes,
        #pragma warning restore CS1591
        [EnumMember(Value = "personalNotes desc")]
        #pragma warning disable CS1591
        PersonalNotesDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "phones")]
        #pragma warning disable CS1591
        Phones,
        #pragma warning restore CS1591
        [EnumMember(Value = "phones desc")]
        #pragma warning disable CS1591
        PhonesDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "postalAddresses")]
        #pragma warning disable CS1591
        PostalAddresses,
        #pragma warning restore CS1591
        [EnumMember(Value = "postalAddresses desc")]
        #pragma warning disable CS1591
        PostalAddressesDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "profession")]
        #pragma warning disable CS1591
        Profession,
        #pragma warning restore CS1591
        [EnumMember(Value = "profession desc")]
        #pragma warning disable CS1591
        ProfessionDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "spouseName")]
        #pragma warning disable CS1591
        SpouseName,
        #pragma warning restore CS1591
        [EnumMember(Value = "spouseName desc")]
        #pragma warning disable CS1591
        SpouseNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "surname")]
        #pragma warning disable CS1591
        Surname,
        #pragma warning restore CS1591
        [EnumMember(Value = "surname desc")]
        #pragma warning disable CS1591
        SurnameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "title")]
        #pragma warning disable CS1591
        Title,
        #pragma warning restore CS1591
        [EnumMember(Value = "title desc")]
        #pragma warning disable CS1591
        TitleDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "websites")]
        #pragma warning disable CS1591
        Websites,
        #pragma warning restore CS1591
        [EnumMember(Value = "websites desc")]
        #pragma warning disable CS1591
        WebsitesDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "weddingAnniversary")]
        #pragma warning disable CS1591
        WeddingAnniversary,
        #pragma warning restore CS1591
        [EnumMember(Value = "weddingAnniversary desc")]
        #pragma warning disable CS1591
        WeddingAnniversaryDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "yomiCompanyName")]
        #pragma warning disable CS1591
        YomiCompanyName,
        #pragma warning restore CS1591
        [EnumMember(Value = "yomiCompanyName desc")]
        #pragma warning disable CS1591
        YomiCompanyNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "yomiGivenName")]
        #pragma warning disable CS1591
        YomiGivenName,
        #pragma warning restore CS1591
        [EnumMember(Value = "yomiGivenName desc")]
        #pragma warning disable CS1591
        YomiGivenNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "yomiSurname")]
        #pragma warning disable CS1591
        YomiSurname,
        #pragma warning restore CS1591
        [EnumMember(Value = "yomiSurname desc")]
        #pragma warning disable CS1591
        YomiSurnameDesc,
        #pragma warning restore CS1591
    }
}
