// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models.Ediscovery {
    public enum LegalHoldStatus {
        [EnumMember(Value = "Pending")]
        Pending,
        [EnumMember(Value = "Error")]
        Error,
        [EnumMember(Value = "Success")]
        Success,
        [EnumMember(Value = "UnknownFutureValue")]
        UnknownFutureValue,
    }
}
