// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models.Security
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserMailboxSetting
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "junkMailDeletion")]
        #pragma warning disable CS1591
        JunkMailDeletion,
        #pragma warning restore CS1591
        [EnumMember(Value = "isFromAddressInAddressBook")]
        #pragma warning disable CS1591
        IsFromAddressInAddressBook,
        #pragma warning restore CS1591
        [EnumMember(Value = "isFromAddressInAddressSafeList")]
        #pragma warning disable CS1591
        IsFromAddressInAddressSafeList,
        #pragma warning restore CS1591
        [EnumMember(Value = "isFromAddressInAddressBlockList")]
        #pragma warning disable CS1591
        IsFromAddressInAddressBlockList,
        #pragma warning restore CS1591
        [EnumMember(Value = "isFromAddressInAddressImplicitSafeList")]
        #pragma warning disable CS1591
        IsFromAddressInAddressImplicitSafeList,
        #pragma warning restore CS1591
        [EnumMember(Value = "isFromAddressInAddressImplicitJunkList")]
        #pragma warning disable CS1591
        IsFromAddressInAddressImplicitJunkList,
        #pragma warning restore CS1591
        [EnumMember(Value = "isFromDomainInDomainSafeList")]
        #pragma warning disable CS1591
        IsFromDomainInDomainSafeList,
        #pragma warning restore CS1591
        [EnumMember(Value = "isFromDomainInDomainBlockList")]
        #pragma warning disable CS1591
        IsFromDomainInDomainBlockList,
        #pragma warning restore CS1591
        [EnumMember(Value = "isRecipientInRecipientSafeList")]
        #pragma warning disable CS1591
        IsRecipientInRecipientSafeList,
        #pragma warning restore CS1591
        [EnumMember(Value = "customRule")]
        #pragma warning disable CS1591
        CustomRule,
        #pragma warning restore CS1591
        [EnumMember(Value = "junkMailRule")]
        #pragma warning disable CS1591
        JunkMailRule,
        #pragma warning restore CS1591
        [EnumMember(Value = "senderPraPresent")]
        #pragma warning disable CS1591
        SenderPraPresent,
        #pragma warning restore CS1591
        [EnumMember(Value = "fromFirstTimeSender")]
        #pragma warning disable CS1591
        FromFirstTimeSender,
        #pragma warning restore CS1591
        [EnumMember(Value = "exclusive")]
        #pragma warning disable CS1591
        Exclusive,
        #pragma warning restore CS1591
        [EnumMember(Value = "priorSeenPass")]
        #pragma warning disable CS1591
        PriorSeenPass,
        #pragma warning restore CS1591
        [EnumMember(Value = "senderAuthenticationSucceeded")]
        #pragma warning disable CS1591
        SenderAuthenticationSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "isJunkMailRuleEnabled")]
        #pragma warning disable CS1591
        IsJunkMailRuleEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknownFutureValue")]
        #pragma warning disable CS1591
        UnknownFutureValue,
        #pragma warning restore CS1591
    }
}
