// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Me.Profile
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>Provides operations to manage the profile property of the microsoft.graph.user entity.</summary>
    public enum GetExpandQueryParameterType
    {
        [EnumMember(Value = "*")]
        #pragma warning disable CS1591
        Asterisk,
        #pragma warning restore CS1591
        [EnumMember(Value = "account")]
        #pragma warning disable CS1591
        Account,
        #pragma warning restore CS1591
        [EnumMember(Value = "addresses")]
        #pragma warning disable CS1591
        Addresses,
        #pragma warning restore CS1591
        [EnumMember(Value = "anniversaries")]
        #pragma warning disable CS1591
        Anniversaries,
        #pragma warning restore CS1591
        [EnumMember(Value = "awards")]
        #pragma warning disable CS1591
        Awards,
        #pragma warning restore CS1591
        [EnumMember(Value = "certifications")]
        #pragma warning disable CS1591
        Certifications,
        #pragma warning restore CS1591
        [EnumMember(Value = "educationalActivities")]
        #pragma warning disable CS1591
        EducationalActivities,
        #pragma warning restore CS1591
        [EnumMember(Value = "emails")]
        #pragma warning disable CS1591
        Emails,
        #pragma warning restore CS1591
        [EnumMember(Value = "interests")]
        #pragma warning disable CS1591
        Interests,
        #pragma warning restore CS1591
        [EnumMember(Value = "languages")]
        #pragma warning disable CS1591
        Languages,
        #pragma warning restore CS1591
        [EnumMember(Value = "names")]
        #pragma warning disable CS1591
        Names,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes")]
        #pragma warning disable CS1591
        Notes,
        #pragma warning restore CS1591
        [EnumMember(Value = "patents")]
        #pragma warning disable CS1591
        Patents,
        #pragma warning restore CS1591
        [EnumMember(Value = "phones")]
        #pragma warning disable CS1591
        Phones,
        #pragma warning restore CS1591
        [EnumMember(Value = "positions")]
        #pragma warning disable CS1591
        Positions,
        #pragma warning restore CS1591
        [EnumMember(Value = "projects")]
        #pragma warning disable CS1591
        Projects,
        #pragma warning restore CS1591
        [EnumMember(Value = "publications")]
        #pragma warning disable CS1591
        Publications,
        #pragma warning restore CS1591
        [EnumMember(Value = "skills")]
        #pragma warning disable CS1591
        Skills,
        #pragma warning restore CS1591
        [EnumMember(Value = "webAccounts")]
        #pragma warning disable CS1591
        WebAccounts,
        #pragma warning restore CS1591
        [EnumMember(Value = "websites")]
        #pragma warning disable CS1591
        Websites,
        #pragma warning restore CS1591
    }
}
