// <auto-generated/>
#pragma warning disable CS0618
using AITGraph.Sdk.Me.Calendar;
using AITGraph.Sdk.Me.CalendarView;
using AITGraph.Sdk.Me.Contacts;
using AITGraph.Sdk.Me.Drive;
using AITGraph.Sdk.Me.MailFolders;
using AITGraph.Sdk.Me.Messages;
using AITGraph.Sdk.Me.Outlook;
using AITGraph.Sdk.Me.Photo;
using AITGraph.Sdk.Me.Profile;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AITGraph.Sdk.Me
{
    /// <summary>
    /// Builds and executes requests for operations under \me
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Provides operations to manage the calendar property of the microsoft.graph.user entity.</summary>
        public global::AITGraph.Sdk.Me.Calendar.CalendarRequestBuilder Calendar
        {
            get => new global::AITGraph.Sdk.Me.Calendar.CalendarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the calendarView property of the microsoft.graph.user entity.</summary>
        public global::AITGraph.Sdk.Me.CalendarView.CalendarViewRequestBuilder CalendarView
        {
            get => new global::AITGraph.Sdk.Me.CalendarView.CalendarViewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the contacts property of the microsoft.graph.user entity.</summary>
        public global::AITGraph.Sdk.Me.Contacts.ContactsRequestBuilder Contacts
        {
            get => new global::AITGraph.Sdk.Me.Contacts.ContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the drive property of the microsoft.graph.user entity.</summary>
        public global::AITGraph.Sdk.Me.Drive.DriveRequestBuilder Drive
        {
            get => new global::AITGraph.Sdk.Me.Drive.DriveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the mailFolders property of the microsoft.graph.user entity.</summary>
        public global::AITGraph.Sdk.Me.MailFolders.MailFoldersRequestBuilder MailFolders
        {
            get => new global::AITGraph.Sdk.Me.MailFolders.MailFoldersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the messages property of the microsoft.graph.user entity.</summary>
        public global::AITGraph.Sdk.Me.Messages.MessagesRequestBuilder Messages
        {
            get => new global::AITGraph.Sdk.Me.Messages.MessagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the outlook property of the microsoft.graph.user entity.</summary>
        public global::AITGraph.Sdk.Me.Outlook.OutlookRequestBuilder Outlook
        {
            get => new global::AITGraph.Sdk.Me.Outlook.OutlookRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the photo property of the microsoft.graph.user entity.</summary>
        public global::AITGraph.Sdk.Me.Photo.PhotoRequestBuilder Photo
        {
            get => new global::AITGraph.Sdk.Me.Photo.PhotoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the profile property of the microsoft.graph.user entity.</summary>
        public global::AITGraph.Sdk.Me.Profile.ProfileRequestBuilder Profile
        {
            get => new global::AITGraph.Sdk.Me.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AITGraph.Sdk.Me.MeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AITGraph.Sdk.Me.MeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
