// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Me.Calendar.Events
{
    /// <summary>Provides operations to manage the events property of the microsoft.graph.calendar entity.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetSelectQueryParameterType
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "categories")]
        #pragma warning disable CS1591
        Categories,
        #pragma warning restore CS1591
        [EnumMember(Value = "changeKey")]
        #pragma warning disable CS1591
        ChangeKey,
        #pragma warning restore CS1591
        [EnumMember(Value = "createdDateTime")]
        #pragma warning disable CS1591
        CreatedDateTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "lastModifiedDateTime")]
        #pragma warning disable CS1591
        LastModifiedDateTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "allowNewTimeProposals")]
        #pragma warning disable CS1591
        AllowNewTimeProposals,
        #pragma warning restore CS1591
        [EnumMember(Value = "attendees")]
        #pragma warning disable CS1591
        Attendees,
        #pragma warning restore CS1591
        [EnumMember(Value = "body")]
        #pragma warning disable CS1591
        Body,
        #pragma warning restore CS1591
        [EnumMember(Value = "bodyPreview")]
        #pragma warning disable CS1591
        BodyPreview,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancelledOccurrences")]
        #pragma warning disable CS1591
        CancelledOccurrences,
        #pragma warning restore CS1591
        [EnumMember(Value = "end")]
        #pragma warning disable CS1591
        End,
        #pragma warning restore CS1591
        [EnumMember(Value = "hasAttachments")]
        #pragma warning disable CS1591
        HasAttachments,
        #pragma warning restore CS1591
        [EnumMember(Value = "hideAttendees")]
        #pragma warning disable CS1591
        HideAttendees,
        #pragma warning restore CS1591
        [EnumMember(Value = "importance")]
        #pragma warning disable CS1591
        Importance,
        #pragma warning restore CS1591
        [EnumMember(Value = "isAllDay")]
        #pragma warning disable CS1591
        IsAllDay,
        #pragma warning restore CS1591
        [EnumMember(Value = "isCancelled")]
        #pragma warning disable CS1591
        IsCancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "isDraft")]
        #pragma warning disable CS1591
        IsDraft,
        #pragma warning restore CS1591
        [EnumMember(Value = "isOnlineMeeting")]
        #pragma warning disable CS1591
        IsOnlineMeeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "isOrganizer")]
        #pragma warning disable CS1591
        IsOrganizer,
        #pragma warning restore CS1591
        [EnumMember(Value = "isReminderOn")]
        #pragma warning disable CS1591
        IsReminderOn,
        #pragma warning restore CS1591
        [EnumMember(Value = "location")]
        #pragma warning disable CS1591
        Location,
        #pragma warning restore CS1591
        [EnumMember(Value = "locations")]
        #pragma warning disable CS1591
        Locations,
        #pragma warning restore CS1591
        [EnumMember(Value = "occurrenceId")]
        #pragma warning disable CS1591
        OccurrenceId,
        #pragma warning restore CS1591
        [EnumMember(Value = "onlineMeeting")]
        #pragma warning disable CS1591
        OnlineMeeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "onlineMeetingProvider")]
        #pragma warning disable CS1591
        OnlineMeetingProvider,
        #pragma warning restore CS1591
        [EnumMember(Value = "onlineMeetingUrl")]
        #pragma warning disable CS1591
        OnlineMeetingUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "organizer")]
        #pragma warning disable CS1591
        Organizer,
        #pragma warning restore CS1591
        [EnumMember(Value = "originalEndTimeZone")]
        #pragma warning disable CS1591
        OriginalEndTimeZone,
        #pragma warning restore CS1591
        [EnumMember(Value = "originalStart")]
        #pragma warning disable CS1591
        OriginalStart,
        #pragma warning restore CS1591
        [EnumMember(Value = "originalStartTimeZone")]
        #pragma warning disable CS1591
        OriginalStartTimeZone,
        #pragma warning restore CS1591
        [EnumMember(Value = "recurrence")]
        #pragma warning disable CS1591
        Recurrence,
        #pragma warning restore CS1591
        [EnumMember(Value = "reminderMinutesBeforeStart")]
        #pragma warning disable CS1591
        ReminderMinutesBeforeStart,
        #pragma warning restore CS1591
        [EnumMember(Value = "responseRequested")]
        #pragma warning disable CS1591
        ResponseRequested,
        #pragma warning restore CS1591
        [EnumMember(Value = "responseStatus")]
        #pragma warning disable CS1591
        ResponseStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "sensitivity")]
        #pragma warning disable CS1591
        Sensitivity,
        #pragma warning restore CS1591
        [EnumMember(Value = "seriesMasterId")]
        #pragma warning disable CS1591
        SeriesMasterId,
        #pragma warning restore CS1591
        [EnumMember(Value = "showAs")]
        #pragma warning disable CS1591
        ShowAs,
        #pragma warning restore CS1591
        [EnumMember(Value = "start")]
        #pragma warning disable CS1591
        Start,
        #pragma warning restore CS1591
        [EnumMember(Value = "subject")]
        #pragma warning disable CS1591
        Subject,
        #pragma warning restore CS1591
        [EnumMember(Value = "transactionId")]
        #pragma warning disable CS1591
        TransactionId,
        #pragma warning restore CS1591
        [EnumMember(Value = "type")]
        #pragma warning disable CS1591
        Type,
        #pragma warning restore CS1591
        [EnumMember(Value = "uid")]
        #pragma warning disable CS1591
        Uid,
        #pragma warning restore CS1591
        [EnumMember(Value = "webLink")]
        #pragma warning disable CS1591
        WebLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "attachments")]
        #pragma warning disable CS1591
        Attachments,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar")]
        #pragma warning disable CS1591
        Calendar,
        #pragma warning restore CS1591
        [EnumMember(Value = "exceptionOccurrences")]
        #pragma warning disable CS1591
        ExceptionOccurrences,
        #pragma warning restore CS1591
        [EnumMember(Value = "extensions")]
        #pragma warning disable CS1591
        Extensions,
        #pragma warning restore CS1591
        [EnumMember(Value = "instances")]
        #pragma warning disable CS1591
        Instances,
        #pragma warning restore CS1591
        [EnumMember(Value = "multiValueExtendedProperties")]
        #pragma warning disable CS1591
        MultiValueExtendedProperties,
        #pragma warning restore CS1591
        [EnumMember(Value = "singleValueExtendedProperties")]
        #pragma warning disable CS1591
        SingleValueExtendedProperties,
        #pragma warning restore CS1591
    }
}
