// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CognitiveServices.Sdk.Models
{
    /// <summary>The supported scenario.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public enum EntitiesEntityPresentationInfo_entityScenario
    {
        [EnumMember(Value = "DominantEntity")]
        #pragma warning disable CS1591
        DominantEntity,
        #pragma warning restore CS1591
        [EnumMember(Value = "DisambiguationItem")]
        #pragma warning disable CS1591
        DisambiguationItem,
        #pragma warning restore CS1591
        [EnumMember(Value = "ListItem")]
        #pragma warning disable CS1591
        ListItem,
        #pragma warning restore CS1591
    }
}
