// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CognitiveServices.Sdk.Models
{
    /// <summary>
    /// Defines a list of relevant webpage links.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class WebWebAnswer : global::CognitiveServices.Sdk.Models.SearchResultsAnswer, IParsable
    {
        /// <summary>A Boolean value that indicates whether the response excluded some results from the answer. If Bing excluded some results, the value is true.</summary>
        public bool? SomeResultsRemoved { get; private set; }
        /// <summary>A list of webpages that are relevant to the query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::CognitiveServices.Sdk.Models.WebPage>? Value { get; set; }
#nullable restore
#else
        public List<global::CognitiveServices.Sdk.Models.WebPage> Value { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CognitiveServices.Sdk.Models.WebWebAnswer"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::CognitiveServices.Sdk.Models.WebWebAnswer CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::CognitiveServices.Sdk.Models.WebWebAnswer();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "someResultsRemoved", n => { SomeResultsRemoved = n.GetBoolValue(); } },
                { "value", n => { Value = n.GetCollectionOfObjectValues<global::CognitiveServices.Sdk.Models.WebPage>(global::CognitiveServices.Sdk.Models.WebPage.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::CognitiveServices.Sdk.Models.WebPage>("value", Value);
        }
    }
}
#pragma warning restore CS0618
