name: Azure DevOps Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.WEBFRONTEND_AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.WEBFRONTEND_AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.WEBFRONTEND_AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
      AZURE_LOCATION: eastus2
      AZURE_CONTAINER_APPS_ENVIRONMENT_NAME: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT_NAME }}
      AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
      AZURE_CONTAINER_APPS_ENVIRONMENT_ID: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
      AZURE_CONTAINER_REGISTRY_ENDPOINT: ${{ secrets.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
      AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID: ${{ secrets.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
      AZURE_LOG_ANALYTICS_WORKSPACE_NAME: ${{ secrets.AZURE_LOG_ANALYTICS_WORKSPACE_NAME }}
      MANAGED_IDENTITY_CLIENT_ID: ${{ secrets.MANAGED_IDENTITY_CLIENT_ID }}
      MANAGED_IDENTITY_NAME: ${{ secrets.MANAGED_IDENTITY_NAME }}
      REGISTRY_PASSWORD: ${{ secrets.WEBFRONTEND_REGISTRY_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.WEBFRONTEND_REGISTRY_USERNAME }}
      AZUREAD__CALLBACKPATH: ${{ secrets.AZUREAD__CALLBACKPATH }}
      AZUREAD__CLIENTID: ${{ secrets.AZUREAD__CLIENTID }}
      AZUREAD__CLIENTSECRET: ${{ secrets.AZUREAD__CLIENTSECRET }}
      AZUREAD__DOMAIN: ${{ secrets.AZUREAD__DOMAIN }}
      AZUREAD__INSTANCE: ${{ secrets.AZUREAD__INSTANCE }}
      AZUREAD__TENANTID: ${{ secrets.AZUREAD__TENANTID }}
      AZUREOPENAIENDPOINT03: ${{ secrets.AZUREOPENAIENDPOINT03 }}
      AZUREOPENAIKEY03: ${{ secrets.AZUREOPENAIKEY03 }}
      AZUREOPENAIMODELNAME02: ${{ secrets.AZUREOPENAIMODELNAME02 }}
      AZUREOPENAIMODELNAME03: ${{ secrets.AZUREOPENAIMODELNAME03 }}
      BING_API_KEY: ${{ secrets.BING_API_KEY }}
      CLIENTID: ${{ secrets.CLIENTID }}
      CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
      DOWNSTREAMAPI__BASEURL: ${{ secrets.DOWNSTREAMAPI__BASEURL }}
      DOWNSTREAMAPI__SCOPES: ${{ secrets.DOWNSTREAMAPI__SCOPES }}
      GTB_TOKEN: ${{ secrets.GTB_TOKEN }}
      SMARTCOMPONENTS__APIKEY: ${{ secrets.SMARTCOMPONENTS__APIKEY }}
      SMARTCOMPONENTS__DEPLOYMENTNAME: ${{ secrets.SMARTCOMPONENTS__DEPLOYMENTNAME }}
      SMARTCOMPONENTS__ENDPOINT: ${{ secrets.SMARTCOMPONENTS__ENDPOINT }}
      STORAGECONNECTIONSTRING: ${{ secrets.STORAGECONNECTIONSTRING }}
      STORAGECONTAINERNAME: ${{ secrets.STORAGECONTAINERNAME }}
      TENANTID: ${{ secrets.TENANTID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Log in with Azure (Client Credentials)
        if: ${{ env.AZURE_CREDENTIALS != '' }}
        run: |
          $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
          Write-Host "::add-mask::$($info.clientSecret)"

          azd auth login `
            --client-id "$($info.clientId)" `
            --client-secret "$($info.clientSecret)" `
            --tenant-id "$($info.tenantId)"
        shell: pwsh

      # Optional steps
      # - name: Provision Infrastructure
      #   run: azd provision --no-prompt
      #   env:
      #     AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}

      # - name: Refresh azd env
      #   run: azd env refresh

      - name: Create azd environment
        run: |
          cd aitrailblazer.AppHost
          azd env new $AZURE_ENV_NAME --subscription $AZURE_SUBSCRIPTION_ID --location $AZURE_LOCATION --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_LOCATION: eastus2

      - name: Set variables in azd environment
        run: |
          cd aitrailblazer.AppHost
          azd env set AZURE_LOCATION $AZURE_LOCATION
          azd env set AZURE_SUBSCRIPTION_ID $AZURE_SUBSCRIPTION_ID
          azd env set AZURE_CONTAINER_APPS_ENVIRONMENT_NAME $AZURE_CONTAINER_APPS_ENVIRONMENT_NAME
          azd env set AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN $AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN
          azd env set AZURE_CONTAINER_APPS_ENVIRONMENT_ID $AZURE_CONTAINER_APPS_ENVIRONMENT_ID
          azd env set AZURE_CONTAINER_REGISTRY_ENDPOINT $AZURE_CONTAINER_REGISTRY_ENDPOINT
          azd env set AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID $AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID
          azd env set AZURE_LOG_ANALYTICS_WORKSPACE_NAME $AZURE_LOG_ANALYTICS_WORKSPACE_NAME
          azd env set MANAGED_IDENTITY_CLIENT_ID $MANAGED_IDENTITY_CLIENT_ID
          azd env set MANAGED_IDENTITY_NAME $MANAGED_IDENTITY_NAME
          azd env set REGISTRY_PASSWORD $REGISTRY_PASSWORD
          azd env set REGISTRY_USERNAME $REGISTRY_USERNAME
          azd env set AZUREAD__CALLBACKPATH $AZUREAD__CALLBACKPATH
          azd env set AZUREAD__CLIENTID $AZUREAD__CLIENTID
          azd env set AZUREAD__CLIENTSECRET $AZUREAD__CLIENTSECRET
          azd env set AZUREAD__DOMAIN $AZUREAD__DOMAIN
          azd env set AZUREAD__INSTANCE $AZUREAD__INSTANCE
          azd env set AZUREAD__TENANTID $AZUREAD__TENANTID
          azd env set AZUREOPENAIENDPOINT03 $AZUREOPENAIENDPOINT03
          azd env set AZUREOPENAIKEY03 $AZUREOPENAIKEY03
          azd env set AZUREOPENAIMODELNAME02 $AZUREOPENAIMODELNAME02
          azd env set AZUREOPENAIMODELNAME03 $AZUREOPENAIMODELNAME03
          azd env set BING_API_KEY $BING_API_KEY
          azd env set CLIENTID $CLIENTID
          azd env set CLIENTSECRET $CLIENTSECRET
          azd env set DOWNSTREAMAPI__BASEURL $DOWNSTREAMAPI__BASEURL
          azd env set DOWNSTREAMAPI__SCOPES $DOWNSTREAMAPI__SCOPES
          azd env set GTB_TOKEN $GTB_TOKEN
          azd env set SMARTCOMPONENTS__APIKEY $SMARTCOMPONENTS__APIKEY
          azd env set SMARTCOMPONENTS__DEPLOYMENTNAME $SMARTCOMPONENTS__DEPLOYMENTNAME
          azd env set SMARTCOMPONENTS__ENDPOINT $SMARTCOMPONENTS__ENDPOINT
          azd env set STORAGECONNECTIONSTRING $STORAGECONNECTIONSTRING
          azd env set STORAGECONTAINERNAME $STORAGECONTAINERNAME
          azd env set TENANTID $TENANTID

      - name: Deploy Application
        run: |
          cd aitrailblazer.AppHost
          azd config set alpha.aca.persistDomains on
          azd deploy --no-prompt
        env:
            AZURE_CLIENT_ID: ${{ secrets.WEBFRONTEND_AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.WEBFRONTEND_AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.WEBFRONTEND_AZURE_SUBSCRIPTION_ID }}
            AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
            AZURE_LOCATION: eastus2
            AZURE_CONTAINER_APPS_ENVIRONMENT_NAME: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT_NAME }}
            AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
            AZURE_CONTAINER_APPS_ENVIRONMENT_ID: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
            AZURE_CONTAINER_REGISTRY_ENDPOINT: ${{ secrets.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
            AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID: ${{ secrets.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
            AZURE_LOG_ANALYTICS_WORKSPACE_NAME: ${{ secrets.AZURE_LOG_ANALYTICS_WORKSPACE_NAME }}
            MANAGED_IDENTITY_CLIENT_ID: ${{ secrets.MANAGED_IDENTITY_CLIENT_ID }}
            MANAGED_IDENTITY_NAME: ${{ secrets.MANAGED_IDENTITY_NAME }}
            REGISTRY_PASSWORD: ${{ secrets.WEBFRONTEND_REGISTRY_PASSWORD }}
            REGISTRY_USERNAME: ${{ secrets.WEBFRONTEND_REGISTRY_USERNAME }}
            AZUREAD__CALLBACKPATH: ${{ secrets.AZUREAD__CALLBACKPATH }}
            AZUREAD__CLIENTID: ${{ secrets.AZUREAD__CLIENTID }}
            AZUREAD__CLIENTSECRET: ${{ secrets.AZUREAD__CLIENTSECRET }}
            AZUREAD__DOMAIN: ${{ secrets.AZUREAD__DOMAIN }}
            AZUREAD__INSTANCE: ${{ secrets.AZUREAD__INSTANCE }}
            AZUREAD__TENANTID: ${{ secrets.AZUREAD__TENANTID }}
            AZUREOPENAIENDPOINT03: ${{ secrets.AZUREOPENAIENDPOINT03 }}
            AZUREOPENAIKEY03: ${{ secrets.AZUREOPENAIKEY03 }}
            AZUREOPENAIMODELNAME02: ${{ secrets.AZUREOPENAIMODELNAME02 }}
            AZUREOPENAIMODELNAME03: ${{ secrets.AZUREOPENAIMODELNAME03 }}
            BING_API_KEY: ${{ secrets.BING_API_KEY }}
            CLIENTID: ${{ secrets.CLIENTID }}
            CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
            DOWNSTREAMAPI__BASEURL: ${{ secrets.DOWNSTREAMAPI__BASEURL }}
            DOWNSTREAMAPI__SCOPES: ${{ secrets.DOWNSTREAMAPI__SCOPES }}
            GTB_TOKEN: ${{ secrets.GTB_TOKEN }}
            SMARTCOMPONENTS__APIKEY: ${{ secrets.SMARTCOMPONENTS__APIKEY }}
            SMARTCOMPONENTS__DEPLOYMENTNAME: ${{ secrets.SMARTCOMPONENTS__DEPLOYMENTNAME }}
            SMARTCOMPONENTS__ENDPOINT: ${{ secrets.SMARTCOMPONENTS__ENDPOINT }}
            STORAGECONNECTIONSTRING: ${{ secrets.STORAGECONNECTIONSTRING }}
            STORAGECONTAINERNAME: ${{ secrets.STORAGECONTAINERNAME }}
            TENANTID: ${{ secrets.TENANTID }}
            DOTNET_ROOT: /usr/share/dotnet