// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models {
    public enum AccountTargetContentType {
        [EnumMember(Value = "unknown")]
        Unknown,
        [EnumMember(Value = "includeAll")]
        IncludeAll,
        [EnumMember(Value = "addressBook")]
        AddressBook,
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
