// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    /// <summary>
    /// Contains properties and inherited properties for Android Managed Store Apps.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AndroidManagedStoreApp : global::AITGraph.Sdk.Models.MobileApp, IParsable
    {
        /// <summary>The Identity Name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppIdentifier { get; set; }
#nullable restore
#else
        public string AppIdentifier { get; set; }
#endif
        /// <summary>The Play for Work Store app URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppStoreUrl { get; set; }
#nullable restore
#else
        public string AppStoreUrl { get; set; }
#endif
        /// <summary>The tracks that are visible to this enterprise.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.AndroidManagedStoreAppTrack>? AppTracks { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.AndroidManagedStoreAppTrack> AppTracks { get; set; }
#endif
        /// <summary>Indicates whether the app is only available to a given enterprise&apos;s users.</summary>
        public bool? IsPrivate { get; set; }
        /// <summary>Indicates whether the app is a preinstalled system app.</summary>
        public bool? IsSystemApp { get; set; }
        /// <summary>The package identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PackageId { get; set; }
#nullable restore
#else
        public string PackageId { get; set; }
#endif
        /// <summary>Whether this app supports OEMConfig policy.</summary>
        public bool? SupportsOemConfig { get; set; }
        /// <summary>The total number of VPP licenses.</summary>
        public int? TotalLicenseCount { get; set; }
        /// <summary>The number of VPP licenses in use.</summary>
        public int? UsedLicenseCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::AITGraph.Sdk.Models.AndroidManagedStoreApp"/> and sets the default values.
        /// </summary>
        public AndroidManagedStoreApp() : base()
        {
            OdataType = "#microsoft.graph.androidManagedStoreApp";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.AndroidManagedStoreApp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::AITGraph.Sdk.Models.AndroidManagedStoreApp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("@odata.type")?.GetStringValue();
            return mappingValue switch
            {
                "#microsoft.graph.androidManagedStoreWebApp" => new global::AITGraph.Sdk.Models.AndroidManagedStoreWebApp(),
                _ => new global::AITGraph.Sdk.Models.AndroidManagedStoreApp(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "appIdentifier", n => { AppIdentifier = n.GetStringValue(); } },
                { "appStoreUrl", n => { AppStoreUrl = n.GetStringValue(); } },
                { "appTracks", n => { AppTracks = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.AndroidManagedStoreAppTrack>(global::AITGraph.Sdk.Models.AndroidManagedStoreAppTrack.CreateFromDiscriminatorValue)?.AsList(); } },
                { "isPrivate", n => { IsPrivate = n.GetBoolValue(); } },
                { "isSystemApp", n => { IsSystemApp = n.GetBoolValue(); } },
                { "packageId", n => { PackageId = n.GetStringValue(); } },
                { "supportsOemConfig", n => { SupportsOemConfig = n.GetBoolValue(); } },
                { "totalLicenseCount", n => { TotalLicenseCount = n.GetIntValue(); } },
                { "usedLicenseCount", n => { UsedLicenseCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("appIdentifier", AppIdentifier);
            writer.WriteStringValue("appStoreUrl", AppStoreUrl);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.AndroidManagedStoreAppTrack>("appTracks", AppTracks);
            writer.WriteBoolValue("isPrivate", IsPrivate);
            writer.WriteBoolValue("isSystemApp", IsSystemApp);
            writer.WriteStringValue("packageId", PackageId);
            writer.WriteBoolValue("supportsOemConfig", SupportsOemConfig);
            writer.WriteIntValue("totalLicenseCount", TotalLicenseCount);
            writer.WriteIntValue("usedLicenseCount", UsedLicenseCount);
        }
    }
}
#pragma warning restore CS0618
