// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ChatMessageActions
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "reactionAdded")]
        #pragma warning disable CS1591
        ReactionAdded,
        #pragma warning restore CS1591
        [EnumMember(Value = "reactionRemoved")]
        #pragma warning disable CS1591
        ReactionRemoved,
        #pragma warning restore CS1591
        [EnumMember(Value = "actionUndefined")]
        #pragma warning disable CS1591
        ActionUndefined,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknownFutureValue")]
        #pragma warning disable CS1591
        UnknownFutureValue,
        #pragma warning restore CS1591
    }
}
