// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ColumnDefinition : global::AITGraph.Sdk.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>This column stores boolean values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.BooleanColumn? Boolean { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.BooleanColumn Boolean { get; set; }
#endif
        /// <summary>This column&apos;s data is calculated based on other columns.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.CalculatedColumn? Calculated { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.CalculatedColumn Calculated { get; set; }
#endif
        /// <summary>This column stores data from a list of choices.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.ChoiceColumn? Choice { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.ChoiceColumn Choice { get; set; }
#endif
        /// <summary>For site columns, the name of the group this column belongs to. Helps organize related columns.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColumnGroup { get; set; }
#nullable restore
#else
        public string ColumnGroup { get; set; }
#endif
        /// <summary>This column stores content approval status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.ContentApprovalStatusColumn? ContentApprovalStatus { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.ContentApprovalStatusColumn ContentApprovalStatus { get; set; }
#endif
        /// <summary>This column stores currency values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.CurrencyColumn? Currency { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.CurrencyColumn Currency { get; set; }
#endif
        /// <summary>This column stores DateTime values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.DateTimeColumn? DateTime { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.DateTimeColumn DateTime { get; set; }
#endif
        /// <summary>The default value for this column.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.DefaultColumnValue? DefaultValue { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.DefaultColumnValue DefaultValue { get; set; }
#endif
        /// <summary>The user-facing description of the column.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The user-facing name of the column.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>If true, no two list items may have the same value for this column.</summary>
        public bool? EnforceUniqueValues { get; set; }
        /// <summary>This column stores a geolocation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.GeolocationColumn? Geolocation { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.GeolocationColumn Geolocation { get; set; }
#endif
        /// <summary>Specifies whether the column is displayed in the user interface.</summary>
        public bool? Hidden { get; set; }
        /// <summary>This column stores hyperlink or picture values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.HyperlinkOrPictureColumn? HyperlinkOrPicture { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.HyperlinkOrPictureColumn HyperlinkOrPicture { get; set; }
#endif
        /// <summary>Specifies whether the column values can used for sorting and searching.</summary>
        public bool? Indexed { get; set; }
        /// <summary>Indicates whether this column can be deleted.</summary>
        public bool? IsDeletable { get; set; }
        /// <summary>Indicates whether values in the column can be reordered. Read-only.</summary>
        public bool? IsReorderable { get; set; }
        /// <summary>Specifies whether the column can be changed.</summary>
        public bool? IsSealed { get; set; }
        /// <summary>This column&apos;s data is looked up from another source in the site.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.LookupColumn? Lookup { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.LookupColumn Lookup { get; set; }
#endif
        /// <summary>The API-facing name of the column as it appears in the [fields][] on a [listItem][]. For the user-facing name, see displayName.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>This column stores number values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.NumberColumn? Number { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.NumberColumn Number { get; set; }
#endif
        /// <summary>This column stores Person or Group values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.PersonOrGroupColumn? PersonOrGroup { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.PersonOrGroupColumn PersonOrGroup { get; set; }
#endif
        /// <summary>If true, changes to this column will be propagated to lists that implement the column.</summary>
        public bool? PropagateChanges { get; set; }
        /// <summary>Specifies whether the column values can be modified.</summary>
        public bool? ReadOnly { get; set; }
        /// <summary>Specifies whether the column value isn&apos;t optional.</summary>
        public bool? Required { get; set; }
        /// <summary>The source column for content type column.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.ColumnDefinition? SourceColumn { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.ColumnDefinition SourceColumn { get; set; }
#endif
        /// <summary>ContentType from which this column is inherited from. Used only to fetch contentTypes columns.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.ContentTypeInfo? SourceContentType { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.ContentTypeInfo SourceContentType { get; set; }
#endif
        /// <summary>This column stores taxonomy terms.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.TermColumn? Term { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.TermColumn Term { get; set; }
#endif
        /// <summary>This column stores text values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.TextColumn? Text { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.TextColumn Text { get; set; }
#endif
        /// <summary>This column stores thumbnail values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.ThumbnailColumn? Thumbnail { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.ThumbnailColumn Thumbnail { get; set; }
#endif
        /// <summary>For site columns, the type of column. Read-only.</summary>
        public global::AITGraph.Sdk.Models.ColumnTypes? Type { get; set; }
        /// <summary>This column stores validation formula and message for the column.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.ColumnValidation? Validation { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.ColumnValidation Validation { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.ColumnDefinition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::AITGraph.Sdk.Models.ColumnDefinition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AITGraph.Sdk.Models.ColumnDefinition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "boolean", n => { Boolean = n.GetObjectValue<global::AITGraph.Sdk.Models.BooleanColumn>(global::AITGraph.Sdk.Models.BooleanColumn.CreateFromDiscriminatorValue); } },
                { "calculated", n => { Calculated = n.GetObjectValue<global::AITGraph.Sdk.Models.CalculatedColumn>(global::AITGraph.Sdk.Models.CalculatedColumn.CreateFromDiscriminatorValue); } },
                { "choice", n => { Choice = n.GetObjectValue<global::AITGraph.Sdk.Models.ChoiceColumn>(global::AITGraph.Sdk.Models.ChoiceColumn.CreateFromDiscriminatorValue); } },
                { "columnGroup", n => { ColumnGroup = n.GetStringValue(); } },
                { "contentApprovalStatus", n => { ContentApprovalStatus = n.GetObjectValue<global::AITGraph.Sdk.Models.ContentApprovalStatusColumn>(global::AITGraph.Sdk.Models.ContentApprovalStatusColumn.CreateFromDiscriminatorValue); } },
                { "currency", n => { Currency = n.GetObjectValue<global::AITGraph.Sdk.Models.CurrencyColumn>(global::AITGraph.Sdk.Models.CurrencyColumn.CreateFromDiscriminatorValue); } },
                { "dateTime", n => { DateTime = n.GetObjectValue<global::AITGraph.Sdk.Models.DateTimeColumn>(global::AITGraph.Sdk.Models.DateTimeColumn.CreateFromDiscriminatorValue); } },
                { "defaultValue", n => { DefaultValue = n.GetObjectValue<global::AITGraph.Sdk.Models.DefaultColumnValue>(global::AITGraph.Sdk.Models.DefaultColumnValue.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "enforceUniqueValues", n => { EnforceUniqueValues = n.GetBoolValue(); } },
                { "geolocation", n => { Geolocation = n.GetObjectValue<global::AITGraph.Sdk.Models.GeolocationColumn>(global::AITGraph.Sdk.Models.GeolocationColumn.CreateFromDiscriminatorValue); } },
                { "hidden", n => { Hidden = n.GetBoolValue(); } },
                { "hyperlinkOrPicture", n => { HyperlinkOrPicture = n.GetObjectValue<global::AITGraph.Sdk.Models.HyperlinkOrPictureColumn>(global::AITGraph.Sdk.Models.HyperlinkOrPictureColumn.CreateFromDiscriminatorValue); } },
                { "indexed", n => { Indexed = n.GetBoolValue(); } },
                { "isDeletable", n => { IsDeletable = n.GetBoolValue(); } },
                { "isReorderable", n => { IsReorderable = n.GetBoolValue(); } },
                { "isSealed", n => { IsSealed = n.GetBoolValue(); } },
                { "lookup", n => { Lookup = n.GetObjectValue<global::AITGraph.Sdk.Models.LookupColumn>(global::AITGraph.Sdk.Models.LookupColumn.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "number", n => { Number = n.GetObjectValue<global::AITGraph.Sdk.Models.NumberColumn>(global::AITGraph.Sdk.Models.NumberColumn.CreateFromDiscriminatorValue); } },
                { "personOrGroup", n => { PersonOrGroup = n.GetObjectValue<global::AITGraph.Sdk.Models.PersonOrGroupColumn>(global::AITGraph.Sdk.Models.PersonOrGroupColumn.CreateFromDiscriminatorValue); } },
                { "propagateChanges", n => { PropagateChanges = n.GetBoolValue(); } },
                { "readOnly", n => { ReadOnly = n.GetBoolValue(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
                { "sourceColumn", n => { SourceColumn = n.GetObjectValue<global::AITGraph.Sdk.Models.ColumnDefinition>(global::AITGraph.Sdk.Models.ColumnDefinition.CreateFromDiscriminatorValue); } },
                { "sourceContentType", n => { SourceContentType = n.GetObjectValue<global::AITGraph.Sdk.Models.ContentTypeInfo>(global::AITGraph.Sdk.Models.ContentTypeInfo.CreateFromDiscriminatorValue); } },
                { "term", n => { Term = n.GetObjectValue<global::AITGraph.Sdk.Models.TermColumn>(global::AITGraph.Sdk.Models.TermColumn.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetObjectValue<global::AITGraph.Sdk.Models.TextColumn>(global::AITGraph.Sdk.Models.TextColumn.CreateFromDiscriminatorValue); } },
                { "thumbnail", n => { Thumbnail = n.GetObjectValue<global::AITGraph.Sdk.Models.ThumbnailColumn>(global::AITGraph.Sdk.Models.ThumbnailColumn.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::AITGraph.Sdk.Models.ColumnTypes>(); } },
                { "validation", n => { Validation = n.GetObjectValue<global::AITGraph.Sdk.Models.ColumnValidation>(global::AITGraph.Sdk.Models.ColumnValidation.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.BooleanColumn>("boolean", Boolean);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.CalculatedColumn>("calculated", Calculated);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.ChoiceColumn>("choice", Choice);
            writer.WriteStringValue("columnGroup", ColumnGroup);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.ContentApprovalStatusColumn>("contentApprovalStatus", ContentApprovalStatus);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.CurrencyColumn>("currency", Currency);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.DateTimeColumn>("dateTime", DateTime);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.DefaultColumnValue>("defaultValue", DefaultValue);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteBoolValue("enforceUniqueValues", EnforceUniqueValues);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.GeolocationColumn>("geolocation", Geolocation);
            writer.WriteBoolValue("hidden", Hidden);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.HyperlinkOrPictureColumn>("hyperlinkOrPicture", HyperlinkOrPicture);
            writer.WriteBoolValue("indexed", Indexed);
            writer.WriteBoolValue("isDeletable", IsDeletable);
            writer.WriteBoolValue("isReorderable", IsReorderable);
            writer.WriteBoolValue("isSealed", IsSealed);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.LookupColumn>("lookup", Lookup);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.NumberColumn>("number", Number);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.PersonOrGroupColumn>("personOrGroup", PersonOrGroup);
            writer.WriteBoolValue("propagateChanges", PropagateChanges);
            writer.WriteBoolValue("readOnly", ReadOnly);
            writer.WriteBoolValue("required", Required);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.ColumnDefinition>("sourceColumn", SourceColumn);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.ContentTypeInfo>("sourceContentType", SourceContentType);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.TermColumn>("term", Term);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.TextColumn>("text", Text);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.ThumbnailColumn>("thumbnail", Thumbnail);
            writer.WriteEnumValue<global::AITGraph.Sdk.Models.ColumnTypes>("type", Type);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.ColumnValidation>("validation", Validation);
        }
    }
}
#pragma warning restore CS0618
