// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    /// <summary>
    /// Blocked actions on the company portal as per platform and device ownership types
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompanyPortalBlockedAction : IAdditionalDataHolder, IParsable
    {
        /// <summary>Action on a device that can be executed in the Company Portal</summary>
        public global::AITGraph.Sdk.Models.CompanyPortalAction? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>Owner type of device.</summary>
        public global::AITGraph.Sdk.Models.OwnerType? OwnerType { get; set; }
        /// <summary>Supported platform types.</summary>
        public global::AITGraph.Sdk.Models.DevicePlatformType? Platform { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::AITGraph.Sdk.Models.CompanyPortalBlockedAction"/> and sets the default values.
        /// </summary>
        public CompanyPortalBlockedAction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.CompanyPortalBlockedAction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AITGraph.Sdk.Models.CompanyPortalBlockedAction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AITGraph.Sdk.Models.CompanyPortalBlockedAction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::AITGraph.Sdk.Models.CompanyPortalAction>(); } },
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
                { "ownerType", n => { OwnerType = n.GetEnumValue<global::AITGraph.Sdk.Models.OwnerType>(); } },
                { "platform", n => { Platform = n.GetEnumValue<global::AITGraph.Sdk.Models.DevicePlatformType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::AITGraph.Sdk.Models.CompanyPortalAction>("action", Action);
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteEnumValue<global::AITGraph.Sdk.Models.OwnerType>("ownerType", OwnerType);
            writer.WriteEnumValue<global::AITGraph.Sdk.Models.DevicePlatformType>("platform", Platform);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
