// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models
{
    /// <summary>Supported setting types</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeviceManagementConfigurationSettingUsage
    {
        /// <summary>No setting type specified</summary>
        [EnumMember(Value = "none")]
        None,
        /// <summary>Configuration setting</summary>
        [EnumMember(Value = "configuration")]
        Configuration,
        /// <summary>Compliance setting</summary>
        [EnumMember(Value = "compliance")]
        Compliance,
    }
}
