// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DirectoryObject : global::AITGraph.Sdk.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Date and time when this object was deleted. Always null when the object hasn&apos;t been deleted.</summary>
        public DateTimeOffset? DeletedDateTime { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.DirectoryObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::AITGraph.Sdk.Models.DirectoryObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("@odata.type")?.GetStringValue();
            return mappingValue switch
            {
                "#microsoft.graph.activityBasedTimeoutPolicy" => new global::AITGraph.Sdk.Models.ActivityBasedTimeoutPolicy(),
                "#microsoft.graph.administrativeUnit" => new global::AITGraph.Sdk.Models.AdministrativeUnit(),
                "#microsoft.graph.application" => new global::AITGraph.Sdk.Models.Application(),
                "#microsoft.graph.appManagementPolicy" => new global::AITGraph.Sdk.Models.AppManagementPolicy(),
                "#microsoft.graph.authorizationPolicy" => new global::AITGraph.Sdk.Models.AuthorizationPolicy(),
                "#microsoft.graph.claimsMappingPolicy" => new global::AITGraph.Sdk.Models.ClaimsMappingPolicy(),
                "#microsoft.graph.contract" => new global::AITGraph.Sdk.Models.Contract(),
                "#microsoft.graph.crossTenantAccessPolicy" => new global::AITGraph.Sdk.Models.CrossTenantAccessPolicy(),
                "#microsoft.graph.device" => new global::AITGraph.Sdk.Models.Device(),
                "#microsoft.graph.directoryObjectPartnerReference" => new global::AITGraph.Sdk.Models.DirectoryObjectPartnerReference(),
                "#microsoft.graph.directoryRole" => new global::AITGraph.Sdk.Models.DirectoryRole(),
                "#microsoft.graph.directoryRoleTemplate" => new global::AITGraph.Sdk.Models.DirectoryRoleTemplate(),
                "#microsoft.graph.directorySettingTemplate" => new global::AITGraph.Sdk.Models.DirectorySettingTemplate(),
                "#microsoft.graph.endpoint" => new global::AITGraph.Sdk.Models.Endpoint(),
                "#microsoft.graph.extensionProperty" => new global::AITGraph.Sdk.Models.ExtensionProperty(),
                "#microsoft.graph.externalIdentitiesPolicy" => new global::AITGraph.Sdk.Models.ExternalIdentitiesPolicy(),
                "#microsoft.graph.group" => new global::AITGraph.Sdk.Models.Group(),
                "#microsoft.graph.homeRealmDiscoveryPolicy" => new global::AITGraph.Sdk.Models.HomeRealmDiscoveryPolicy(),
                "#microsoft.graph.identitySecurityDefaultsEnforcementPolicy" => new global::AITGraph.Sdk.Models.IdentitySecurityDefaultsEnforcementPolicy(),
                "#microsoft.graph.organization" => new global::AITGraph.Sdk.Models.Organization(),
                "#microsoft.graph.orgContact" => new global::AITGraph.Sdk.Models.OrgContact(),
                "#microsoft.graph.permissionGrantPolicy" => new global::AITGraph.Sdk.Models.PermissionGrantPolicy(),
                "#microsoft.graph.policyBase" => new global::AITGraph.Sdk.Models.PolicyBase(),
                "#microsoft.graph.resourceSpecificPermissionGrant" => new global::AITGraph.Sdk.Models.ResourceSpecificPermissionGrant(),
                "#microsoft.graph.servicePrincipal" => new global::AITGraph.Sdk.Models.ServicePrincipal(),
                "#microsoft.graph.servicePrincipalCreationPolicy" => new global::AITGraph.Sdk.Models.ServicePrincipalCreationPolicy(),
                "#microsoft.graph.stsPolicy" => new global::AITGraph.Sdk.Models.StsPolicy(),
                "#microsoft.graph.tenantAppManagementPolicy" => new global::AITGraph.Sdk.Models.TenantAppManagementPolicy(),
                "#microsoft.graph.tenantRelationshipAccessPolicyBase" => new global::AITGraph.Sdk.Models.TenantRelationshipAccessPolicyBase(),
                "#microsoft.graph.tokenIssuancePolicy" => new global::AITGraph.Sdk.Models.TokenIssuancePolicy(),
                "#microsoft.graph.tokenLifetimePolicy" => new global::AITGraph.Sdk.Models.TokenLifetimePolicy(),
                "#microsoft.graph.user" => new global::AITGraph.Sdk.Models.User(),
                _ => new global::AITGraph.Sdk.Models.DirectoryObject(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "deletedDateTime", n => { DeletedDateTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteDateTimeOffsetValue("deletedDateTime", DeletedDateTime);
        }
    }
}
#pragma warning restore CS0618
