// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EducationFeedbackResourceOutcome : global::AITGraph.Sdk.Models.EducationOutcome, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The actual feedback resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.EducationResource? FeedbackResource { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.EducationResource FeedbackResource { get; set; }
#endif
        /// <summary>The status of the feedback resource. The possible values are: notPublished, pendingPublish, published, failedPublish, unknownFutureValue.</summary>
        public global::AITGraph.Sdk.Models.EducationFeedbackResourceOutcomeStatus? ResourceStatus { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::AITGraph.Sdk.Models.EducationFeedbackResourceOutcome"/> and sets the default values.
        /// </summary>
        public EducationFeedbackResourceOutcome() : base()
        {
            OdataType = "#microsoft.graph.educationFeedbackResourceOutcome";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.EducationFeedbackResourceOutcome"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::AITGraph.Sdk.Models.EducationFeedbackResourceOutcome CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AITGraph.Sdk.Models.EducationFeedbackResourceOutcome();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "feedbackResource", n => { FeedbackResource = n.GetObjectValue<global::AITGraph.Sdk.Models.EducationResource>(global::AITGraph.Sdk.Models.EducationResource.CreateFromDiscriminatorValue); } },
                { "resourceStatus", n => { ResourceStatus = n.GetEnumValue<global::AITGraph.Sdk.Models.EducationFeedbackResourceOutcomeStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.EducationResource>("feedbackResource", FeedbackResource);
            writer.WriteEnumValue<global::AITGraph.Sdk.Models.EducationFeedbackResourceOutcomeStatus>("resourceStatus", ResourceStatus);
        }
    }
}
#pragma warning restore CS0618
