// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InformationProtection : global::AITGraph.Sdk.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The bitlocker property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.Bitlocker? Bitlocker { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.Bitlocker Bitlocker { get; set; }
#endif
        /// <summary>The dataLossPreventionPolicies property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.DataLossPreventionPolicy>? DataLossPreventionPolicies { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.DataLossPreventionPolicy> DataLossPreventionPolicies { get; set; }
#endif
        /// <summary>The policy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.InformationProtectionPolicy? Policy { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.InformationProtectionPolicy Policy { get; set; }
#endif
        /// <summary>The sensitivityLabels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.SensitivityLabel>? SensitivityLabels { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.SensitivityLabel> SensitivityLabels { get; set; }
#endif
        /// <summary>The sensitivityPolicySettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.SensitivityPolicySettings? SensitivityPolicySettings { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.SensitivityPolicySettings SensitivityPolicySettings { get; set; }
#endif
        /// <summary>The threatAssessmentRequests property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.ThreatAssessmentRequest>? ThreatAssessmentRequests { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.ThreatAssessmentRequest> ThreatAssessmentRequests { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.InformationProtection"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::AITGraph.Sdk.Models.InformationProtection CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AITGraph.Sdk.Models.InformationProtection();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "bitlocker", n => { Bitlocker = n.GetObjectValue<global::AITGraph.Sdk.Models.Bitlocker>(global::AITGraph.Sdk.Models.Bitlocker.CreateFromDiscriminatorValue); } },
                { "dataLossPreventionPolicies", n => { DataLossPreventionPolicies = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.DataLossPreventionPolicy>(global::AITGraph.Sdk.Models.DataLossPreventionPolicy.CreateFromDiscriminatorValue)?.AsList(); } },
                { "policy", n => { Policy = n.GetObjectValue<global::AITGraph.Sdk.Models.InformationProtectionPolicy>(global::AITGraph.Sdk.Models.InformationProtectionPolicy.CreateFromDiscriminatorValue); } },
                { "sensitivityLabels", n => { SensitivityLabels = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.SensitivityLabel>(global::AITGraph.Sdk.Models.SensitivityLabel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sensitivityPolicySettings", n => { SensitivityPolicySettings = n.GetObjectValue<global::AITGraph.Sdk.Models.SensitivityPolicySettings>(global::AITGraph.Sdk.Models.SensitivityPolicySettings.CreateFromDiscriminatorValue); } },
                { "threatAssessmentRequests", n => { ThreatAssessmentRequests = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.ThreatAssessmentRequest>(global::AITGraph.Sdk.Models.ThreatAssessmentRequest.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.Bitlocker>("bitlocker", Bitlocker);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.DataLossPreventionPolicy>("dataLossPreventionPolicies", DataLossPreventionPolicies);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.InformationProtectionPolicy>("policy", Policy);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.SensitivityLabel>("sensitivityLabels", SensitivityLabels);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.SensitivityPolicySettings>("sensitivityPolicySettings", SensitivityPolicySettings);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.ThreatAssessmentRequest>("threatAssessmentRequests", ThreatAssessmentRequests);
        }
    }
}
#pragma warning restore CS0618
