// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    /// <summary>
    /// iOS Device Features Configuration Profile.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IosDeviceFeaturesConfiguration : global::AITGraph.Sdk.Models.AppleDeviceFeaturesConfigurationBase, IParsable
    {
        /// <summary>Asset tag information for the device, displayed on the login window and lock screen.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssetTagTemplate { get; set; }
#nullable restore
#else
        public string AssetTagTemplate { get; set; }
#endif
        /// <summary>Gets or sets iOS Web Content Filter settings, supervised mode only</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.IosWebContentFilterBase? ContentFilterSettings { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.IosWebContentFilterBase ContentFilterSettings { get; set; }
#endif
        /// <summary>A list of app and folders to appear on the Home Screen Dock. This collection can contain a maximum of 500 elements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.IosHomeScreenItem>? HomeScreenDockIcons { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.IosHomeScreenItem> HomeScreenDockIcons { get; set; }
#endif
        /// <summary>Gets or sets the number of rows to render when configuring iOS home screen layout settings. If this value is configured, homeScreenGridWidth must be configured as well.</summary>
        public int? HomeScreenGridHeight { get; set; }
        /// <summary>Gets or sets the number of columns to render when configuring iOS home screen layout settings. If this value is configured, homeScreenGridHeight must be configured as well.</summary>
        public int? HomeScreenGridWidth { get; set; }
        /// <summary>A list of pages on the Home Screen. This collection can contain a maximum of 500 elements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.IosHomeScreenPage>? HomeScreenPages { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.IosHomeScreenPage> HomeScreenPages { get; set; }
#endif
        /// <summary>Identity Certificate for the renewal of Kerberos ticket used in single sign-on settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.IosCertificateProfileBase? IdentityCertificateForClientAuthentication { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.IosCertificateProfileBase IdentityCertificateForClientAuthentication { get; set; }
#endif
        /// <summary>Gets or sets a single sign-on extension profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.IosSingleSignOnExtension? IosSingleSignOnExtension { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.IosSingleSignOnExtension IosSingleSignOnExtension { get; set; }
#endif
        /// <summary>A footnote displayed on the login window and lock screen. Available in iOS 9.3.1 and later.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LockScreenFootnote { get; set; }
#nullable restore
#else
        public string LockScreenFootnote { get; set; }
#endif
        /// <summary>Notification settings for each bundle id. Applicable to devices in supervised mode only (iOS 9.3 and later). This collection can contain a maximum of 500 elements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.IosNotificationSettings>? NotificationSettings { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.IosNotificationSettings> NotificationSettings { get; set; }
#endif
        /// <summary>Gets or sets a single sign-on extension profile. Deprecated: use IOSSingleSignOnExtension instead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.SingleSignOnExtension? SingleSignOnExtension { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.SingleSignOnExtension SingleSignOnExtension { get; set; }
#endif
        /// <summary>PKINIT Certificate for the authentication with single sign-on extension settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.IosCertificateProfileBase? SingleSignOnExtensionPkinitCertificate { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.IosCertificateProfileBase SingleSignOnExtensionPkinitCertificate { get; set; }
#endif
        /// <summary>The Kerberos login settings that enable apps on receiving devices to authenticate smoothly.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.IosSingleSignOnSettings? SingleSignOnSettings { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.IosSingleSignOnSettings SingleSignOnSettings { get; set; }
#endif
        /// <summary>An enum type for wallpaper display location specifier.</summary>
        public global::AITGraph.Sdk.Models.IosWallpaperDisplayLocation? WallpaperDisplayLocation { get; set; }
        /// <summary>A wallpaper image must be in either PNG or JPEG format. It requires a supervised device with iOS 8 or later version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.MimeContent? WallpaperImage { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.MimeContent WallpaperImage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AITGraph.Sdk.Models.IosDeviceFeaturesConfiguration"/> and sets the default values.
        /// </summary>
        public IosDeviceFeaturesConfiguration() : base()
        {
            OdataType = "#microsoft.graph.iosDeviceFeaturesConfiguration";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.IosDeviceFeaturesConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::AITGraph.Sdk.Models.IosDeviceFeaturesConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AITGraph.Sdk.Models.IosDeviceFeaturesConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "assetTagTemplate", n => { AssetTagTemplate = n.GetStringValue(); } },
                { "contentFilterSettings", n => { ContentFilterSettings = n.GetObjectValue<global::AITGraph.Sdk.Models.IosWebContentFilterBase>(global::AITGraph.Sdk.Models.IosWebContentFilterBase.CreateFromDiscriminatorValue); } },
                { "homeScreenDockIcons", n => { HomeScreenDockIcons = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.IosHomeScreenItem>(global::AITGraph.Sdk.Models.IosHomeScreenItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "homeScreenGridHeight", n => { HomeScreenGridHeight = n.GetIntValue(); } },
                { "homeScreenGridWidth", n => { HomeScreenGridWidth = n.GetIntValue(); } },
                { "homeScreenPages", n => { HomeScreenPages = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.IosHomeScreenPage>(global::AITGraph.Sdk.Models.IosHomeScreenPage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "identityCertificateForClientAuthentication", n => { IdentityCertificateForClientAuthentication = n.GetObjectValue<global::AITGraph.Sdk.Models.IosCertificateProfileBase>(global::AITGraph.Sdk.Models.IosCertificateProfileBase.CreateFromDiscriminatorValue); } },
                { "iosSingleSignOnExtension", n => { IosSingleSignOnExtension = n.GetObjectValue<global::AITGraph.Sdk.Models.IosSingleSignOnExtension>(global::AITGraph.Sdk.Models.IosSingleSignOnExtension.CreateFromDiscriminatorValue); } },
                { "lockScreenFootnote", n => { LockScreenFootnote = n.GetStringValue(); } },
                { "notificationSettings", n => { NotificationSettings = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.IosNotificationSettings>(global::AITGraph.Sdk.Models.IosNotificationSettings.CreateFromDiscriminatorValue)?.AsList(); } },
                { "singleSignOnExtension", n => { SingleSignOnExtension = n.GetObjectValue<global::AITGraph.Sdk.Models.SingleSignOnExtension>(global::AITGraph.Sdk.Models.SingleSignOnExtension.CreateFromDiscriminatorValue); } },
                { "singleSignOnExtensionPkinitCertificate", n => { SingleSignOnExtensionPkinitCertificate = n.GetObjectValue<global::AITGraph.Sdk.Models.IosCertificateProfileBase>(global::AITGraph.Sdk.Models.IosCertificateProfileBase.CreateFromDiscriminatorValue); } },
                { "singleSignOnSettings", n => { SingleSignOnSettings = n.GetObjectValue<global::AITGraph.Sdk.Models.IosSingleSignOnSettings>(global::AITGraph.Sdk.Models.IosSingleSignOnSettings.CreateFromDiscriminatorValue); } },
                { "wallpaperDisplayLocation", n => { WallpaperDisplayLocation = n.GetEnumValue<global::AITGraph.Sdk.Models.IosWallpaperDisplayLocation>(); } },
                { "wallpaperImage", n => { WallpaperImage = n.GetObjectValue<global::AITGraph.Sdk.Models.MimeContent>(global::AITGraph.Sdk.Models.MimeContent.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("assetTagTemplate", AssetTagTemplate);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.IosWebContentFilterBase>("contentFilterSettings", ContentFilterSettings);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.IosHomeScreenItem>("homeScreenDockIcons", HomeScreenDockIcons);
            writer.WriteIntValue("homeScreenGridHeight", HomeScreenGridHeight);
            writer.WriteIntValue("homeScreenGridWidth", HomeScreenGridWidth);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.IosHomeScreenPage>("homeScreenPages", HomeScreenPages);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.IosCertificateProfileBase>("identityCertificateForClientAuthentication", IdentityCertificateForClientAuthentication);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.IosSingleSignOnExtension>("iosSingleSignOnExtension", IosSingleSignOnExtension);
            writer.WriteStringValue("lockScreenFootnote", LockScreenFootnote);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.IosNotificationSettings>("notificationSettings", NotificationSettings);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.SingleSignOnExtension>("singleSignOnExtension", SingleSignOnExtension);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.IosCertificateProfileBase>("singleSignOnExtensionPkinitCertificate", SingleSignOnExtensionPkinitCertificate);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.IosSingleSignOnSettings>("singleSignOnSettings", SingleSignOnSettings);
            writer.WriteEnumValue<global::AITGraph.Sdk.Models.IosWallpaperDisplayLocation>("wallpaperDisplayLocation", WallpaperDisplayLocation);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.MimeContent>("wallpaperImage", WallpaperImage);
        }
    }
}
#pragma warning restore CS0618
