// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ItemFacet : global::AITGraph.Sdk.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The audiences that are able to see the values contained within the associated entity. Possible values are: me, family, contacts, groupMembers, organization, federatedOrganizations, everyone, unknownFutureValue.</summary>
        public global::AITGraph.Sdk.Models.AllowedAudiences? AllowedAudiences { get; set; }
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.IdentitySet? CreatedBy { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.IdentitySet CreatedBy { get; set; }
#endif
        /// <summary>Provides the dateTimeOffset for when the entity was created.</summary>
        public DateTimeOffset? CreatedDateTime { get; set; }
        /// <summary>Contains inference detail if the entity is inferred by the creating or modifying application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.InferenceData? Inference { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.InferenceData Inference { get; set; }
#endif
        /// <summary>The isSearchable property</summary>
        public bool? IsSearchable { get; set; }
        /// <summary>The lastModifiedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.IdentitySet? LastModifiedBy { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.IdentitySet LastModifiedBy { get; set; }
#endif
        /// <summary>Provides the dateTimeOffset for when the entity was created.</summary>
        public DateTimeOffset? LastModifiedDateTime { get; set; }
        /// <summary>Where the values within an entity originated if synced from another service.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.PersonDataSources? Source { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.PersonDataSources Source { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.ItemFacet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::AITGraph.Sdk.Models.ItemFacet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("@odata.type")?.GetStringValue();
            return mappingValue switch
            {
                "#microsoft.graph.educationalActivity" => new global::AITGraph.Sdk.Models.EducationalActivity(),
                "#microsoft.graph.itemAddress" => new global::AITGraph.Sdk.Models.ItemAddress(),
                "#microsoft.graph.itemEmail" => new global::AITGraph.Sdk.Models.ItemEmail(),
                "#microsoft.graph.itemPatent" => new global::AITGraph.Sdk.Models.ItemPatent(),
                "#microsoft.graph.itemPhone" => new global::AITGraph.Sdk.Models.ItemPhone(),
                "#microsoft.graph.itemPublication" => new global::AITGraph.Sdk.Models.ItemPublication(),
                "#microsoft.graph.languageProficiency" => new global::AITGraph.Sdk.Models.LanguageProficiency(),
                "#microsoft.graph.personAnnotation" => new global::AITGraph.Sdk.Models.PersonAnnotation(),
                "#microsoft.graph.personAnnualEvent" => new global::AITGraph.Sdk.Models.PersonAnnualEvent(),
                "#microsoft.graph.personAward" => new global::AITGraph.Sdk.Models.PersonAward(),
                "#microsoft.graph.personCertification" => new global::AITGraph.Sdk.Models.PersonCertification(),
                "#microsoft.graph.personInterest" => new global::AITGraph.Sdk.Models.PersonInterest(),
                "#microsoft.graph.personName" => new global::AITGraph.Sdk.Models.PersonName(),
                "#microsoft.graph.personResponsibility" => new global::AITGraph.Sdk.Models.PersonResponsibility(),
                "#microsoft.graph.personWebsite" => new global::AITGraph.Sdk.Models.PersonWebsite(),
                "#microsoft.graph.projectParticipation" => new global::AITGraph.Sdk.Models.ProjectParticipation(),
                "#microsoft.graph.skillProficiency" => new global::AITGraph.Sdk.Models.SkillProficiency(),
                "#microsoft.graph.userAccountInformation" => new global::AITGraph.Sdk.Models.UserAccountInformation(),
                "#microsoft.graph.webAccount" => new global::AITGraph.Sdk.Models.WebAccount(),
                "#microsoft.graph.workPosition" => new global::AITGraph.Sdk.Models.WorkPosition(),
                _ => new global::AITGraph.Sdk.Models.ItemFacet(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "allowedAudiences", n => { AllowedAudiences = n.GetEnumValue<global::AITGraph.Sdk.Models.AllowedAudiences>(); } },
                { "createdBy", n => { CreatedBy = n.GetObjectValue<global::AITGraph.Sdk.Models.IdentitySet>(global::AITGraph.Sdk.Models.IdentitySet.CreateFromDiscriminatorValue); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetDateTimeOffsetValue(); } },
                { "inference", n => { Inference = n.GetObjectValue<global::AITGraph.Sdk.Models.InferenceData>(global::AITGraph.Sdk.Models.InferenceData.CreateFromDiscriminatorValue); } },
                { "isSearchable", n => { IsSearchable = n.GetBoolValue(); } },
                { "lastModifiedBy", n => { LastModifiedBy = n.GetObjectValue<global::AITGraph.Sdk.Models.IdentitySet>(global::AITGraph.Sdk.Models.IdentitySet.CreateFromDiscriminatorValue); } },
                { "lastModifiedDateTime", n => { LastModifiedDateTime = n.GetDateTimeOffsetValue(); } },
                { "source", n => { Source = n.GetObjectValue<global::AITGraph.Sdk.Models.PersonDataSources>(global::AITGraph.Sdk.Models.PersonDataSources.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteEnumValue<global::AITGraph.Sdk.Models.AllowedAudiences>("allowedAudiences", AllowedAudiences);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.IdentitySet>("createdBy", CreatedBy);
            writer.WriteDateTimeOffsetValue("createdDateTime", CreatedDateTime);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.InferenceData>("inference", Inference);
            writer.WriteBoolValue("isSearchable", IsSearchable);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.IdentitySet>("lastModifiedBy", LastModifiedBy);
            writer.WriteDateTimeOffsetValue("lastModifiedDateTime", LastModifiedDateTime);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.PersonDataSources>("source", Source);
        }
    }
}
#pragma warning restore CS0618
