// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MlClassificationMatchTolerance
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "exact")]
        #pragma warning disable CS1591
        Exact,
        #pragma warning restore CS1591
        [EnumMember(Value = "near")]
        #pragma warning disable CS1591
        Near,
        #pragma warning restore CS1591
    }
}
