// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models {
    public enum Priority {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "High")]
        High,
        [EnumMember(Value = "Low")]
        Low,
    }
}
