// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RestrictionTrigger
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "copyPaste")]
        #pragma warning disable CS1591
        CopyPaste,
        #pragma warning restore CS1591
        [EnumMember(Value = "copyToNetworkShare")]
        #pragma warning disable CS1591
        CopyToNetworkShare,
        #pragma warning restore CS1591
        [EnumMember(Value = "copyToRemovableMedia")]
        #pragma warning disable CS1591
        CopyToRemovableMedia,
        #pragma warning restore CS1591
        [EnumMember(Value = "screenCapture")]
        #pragma warning disable CS1591
        ScreenCapture,
        #pragma warning restore CS1591
        [EnumMember(Value = "print")]
        #pragma warning disable CS1591
        Print,
        #pragma warning restore CS1591
        [EnumMember(Value = "cloudEgress")]
        #pragma warning disable CS1591
        CloudEgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "unallowedApps")]
        #pragma warning disable CS1591
        UnallowedApps,
        #pragma warning restore CS1591
    }
}
