// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SalesQuote : global::AITGraph.Sdk.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The acceptedDate property</summary>
        public Date? AcceptedDate { get; set; }
        /// <summary>The billingPostalAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.PostalAddressType? BillingPostalAddress { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.PostalAddressType BillingPostalAddress { get; set; }
#endif
        /// <summary>The billToCustomerId property</summary>
        public Guid? BillToCustomerId { get; set; }
        /// <summary>The billToCustomerNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillToCustomerNumber { get; set; }
#nullable restore
#else
        public string BillToCustomerNumber { get; set; }
#endif
        /// <summary>The billToName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillToName { get; set; }
#nullable restore
#else
        public string BillToName { get; set; }
#endif
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.Currency? Currency { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.Currency Currency { get; set; }
#endif
        /// <summary>The currencyCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyCode { get; set; }
#nullable restore
#else
        public string CurrencyCode { get; set; }
#endif
        /// <summary>The currencyId property</summary>
        public Guid? CurrencyId { get; set; }
        /// <summary>The customer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.Customer? Customer { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.Customer Customer { get; set; }
#endif
        /// <summary>The customerId property</summary>
        public Guid? CustomerId { get; set; }
        /// <summary>The customerName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerName { get; set; }
#nullable restore
#else
        public string CustomerName { get; set; }
#endif
        /// <summary>The customerNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerNumber { get; set; }
#nullable restore
#else
        public string CustomerNumber { get; set; }
#endif
        /// <summary>The discountAmount property</summary>
        public decimal? DiscountAmount { get; set; }
        /// <summary>The documentDate property</summary>
        public Date? DocumentDate { get; set; }
        /// <summary>The dueDate property</summary>
        public Date? DueDate { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The externalDocumentNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalDocumentNumber { get; set; }
#nullable restore
#else
        public string ExternalDocumentNumber { get; set; }
#endif
        /// <summary>The lastModifiedDateTime property</summary>
        public DateTimeOffset? LastModifiedDateTime { get; set; }
        /// <summary>The number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>The paymentTerm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.PaymentTerm? PaymentTerm { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.PaymentTerm PaymentTerm { get; set; }
#endif
        /// <summary>The paymentTermsId property</summary>
        public Guid? PaymentTermsId { get; set; }
        /// <summary>The phoneNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>The salesperson property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Salesperson { get; set; }
#nullable restore
#else
        public string Salesperson { get; set; }
#endif
        /// <summary>The salesQuoteLines property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.SalesQuoteLine>? SalesQuoteLines { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.SalesQuoteLine> SalesQuoteLines { get; set; }
#endif
        /// <summary>The sellingPostalAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.PostalAddressType? SellingPostalAddress { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.PostalAddressType SellingPostalAddress { get; set; }
#endif
        /// <summary>The sentDate property</summary>
        public DateTimeOffset? SentDate { get; set; }
        /// <summary>The shipmentMethod property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.ShipmentMethod? ShipmentMethod { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.ShipmentMethod ShipmentMethod { get; set; }
#endif
        /// <summary>The shipmentMethodId property</summary>
        public Guid? ShipmentMethodId { get; set; }
        /// <summary>The shippingPostalAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AITGraph.Sdk.Models.PostalAddressType? ShippingPostalAddress { get; set; }
#nullable restore
#else
        public global::AITGraph.Sdk.Models.PostalAddressType ShippingPostalAddress { get; set; }
#endif
        /// <summary>The shipToContact property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipToContact { get; set; }
#nullable restore
#else
        public string ShipToContact { get; set; }
#endif
        /// <summary>The shipToName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipToName { get; set; }
#nullable restore
#else
        public string ShipToName { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The totalAmountExcludingTax property</summary>
        public decimal? TotalAmountExcludingTax { get; set; }
        /// <summary>The totalAmountIncludingTax property</summary>
        public decimal? TotalAmountIncludingTax { get; set; }
        /// <summary>The totalTaxAmount property</summary>
        public decimal? TotalTaxAmount { get; set; }
        /// <summary>The validUntilDate property</summary>
        public Date? ValidUntilDate { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.SalesQuote"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::AITGraph.Sdk.Models.SalesQuote CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AITGraph.Sdk.Models.SalesQuote();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "acceptedDate", n => { AcceptedDate = n.GetDateValue(); } },
                { "billToCustomerId", n => { BillToCustomerId = n.GetGuidValue(); } },
                { "billToCustomerNumber", n => { BillToCustomerNumber = n.GetStringValue(); } },
                { "billToName", n => { BillToName = n.GetStringValue(); } },
                { "billingPostalAddress", n => { BillingPostalAddress = n.GetObjectValue<global::AITGraph.Sdk.Models.PostalAddressType>(global::AITGraph.Sdk.Models.PostalAddressType.CreateFromDiscriminatorValue); } },
                { "currency", n => { Currency = n.GetObjectValue<global::AITGraph.Sdk.Models.Currency>(global::AITGraph.Sdk.Models.Currency.CreateFromDiscriminatorValue); } },
                { "currencyCode", n => { CurrencyCode = n.GetStringValue(); } },
                { "currencyId", n => { CurrencyId = n.GetGuidValue(); } },
                { "customer", n => { Customer = n.GetObjectValue<global::AITGraph.Sdk.Models.Customer>(global::AITGraph.Sdk.Models.Customer.CreateFromDiscriminatorValue); } },
                { "customerId", n => { CustomerId = n.GetGuidValue(); } },
                { "customerName", n => { CustomerName = n.GetStringValue(); } },
                { "customerNumber", n => { CustomerNumber = n.GetStringValue(); } },
                { "discountAmount", n => { DiscountAmount = n.GetDecimalValue(); } },
                { "documentDate", n => { DocumentDate = n.GetDateValue(); } },
                { "dueDate", n => { DueDate = n.GetDateValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "externalDocumentNumber", n => { ExternalDocumentNumber = n.GetStringValue(); } },
                { "lastModifiedDateTime", n => { LastModifiedDateTime = n.GetDateTimeOffsetValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "paymentTerm", n => { PaymentTerm = n.GetObjectValue<global::AITGraph.Sdk.Models.PaymentTerm>(global::AITGraph.Sdk.Models.PaymentTerm.CreateFromDiscriminatorValue); } },
                { "paymentTermsId", n => { PaymentTermsId = n.GetGuidValue(); } },
                { "phoneNumber", n => { PhoneNumber = n.GetStringValue(); } },
                { "salesQuoteLines", n => { SalesQuoteLines = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.SalesQuoteLine>(global::AITGraph.Sdk.Models.SalesQuoteLine.CreateFromDiscriminatorValue)?.AsList(); } },
                { "salesperson", n => { Salesperson = n.GetStringValue(); } },
                { "sellingPostalAddress", n => { SellingPostalAddress = n.GetObjectValue<global::AITGraph.Sdk.Models.PostalAddressType>(global::AITGraph.Sdk.Models.PostalAddressType.CreateFromDiscriminatorValue); } },
                { "sentDate", n => { SentDate = n.GetDateTimeOffsetValue(); } },
                { "shipToContact", n => { ShipToContact = n.GetStringValue(); } },
                { "shipToName", n => { ShipToName = n.GetStringValue(); } },
                { "shipmentMethod", n => { ShipmentMethod = n.GetObjectValue<global::AITGraph.Sdk.Models.ShipmentMethod>(global::AITGraph.Sdk.Models.ShipmentMethod.CreateFromDiscriminatorValue); } },
                { "shipmentMethodId", n => { ShipmentMethodId = n.GetGuidValue(); } },
                { "shippingPostalAddress", n => { ShippingPostalAddress = n.GetObjectValue<global::AITGraph.Sdk.Models.PostalAddressType>(global::AITGraph.Sdk.Models.PostalAddressType.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "totalAmountExcludingTax", n => { TotalAmountExcludingTax = n.GetDecimalValue(); } },
                { "totalAmountIncludingTax", n => { TotalAmountIncludingTax = n.GetDecimalValue(); } },
                { "totalTaxAmount", n => { TotalTaxAmount = n.GetDecimalValue(); } },
                { "validUntilDate", n => { ValidUntilDate = n.GetDateValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteDateValue("acceptedDate", AcceptedDate);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.PostalAddressType>("billingPostalAddress", BillingPostalAddress);
            writer.WriteGuidValue("billToCustomerId", BillToCustomerId);
            writer.WriteStringValue("billToCustomerNumber", BillToCustomerNumber);
            writer.WriteStringValue("billToName", BillToName);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.Currency>("currency", Currency);
            writer.WriteStringValue("currencyCode", CurrencyCode);
            writer.WriteGuidValue("currencyId", CurrencyId);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.Customer>("customer", Customer);
            writer.WriteGuidValue("customerId", CustomerId);
            writer.WriteStringValue("customerName", CustomerName);
            writer.WriteStringValue("customerNumber", CustomerNumber);
            writer.WriteDecimalValue("discountAmount", DiscountAmount);
            writer.WriteDateValue("documentDate", DocumentDate);
            writer.WriteDateValue("dueDate", DueDate);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("externalDocumentNumber", ExternalDocumentNumber);
            writer.WriteDateTimeOffsetValue("lastModifiedDateTime", LastModifiedDateTime);
            writer.WriteStringValue("number", Number);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.PaymentTerm>("paymentTerm", PaymentTerm);
            writer.WriteGuidValue("paymentTermsId", PaymentTermsId);
            writer.WriteStringValue("phoneNumber", PhoneNumber);
            writer.WriteStringValue("salesperson", Salesperson);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.SalesQuoteLine>("salesQuoteLines", SalesQuoteLines);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.PostalAddressType>("sellingPostalAddress", SellingPostalAddress);
            writer.WriteDateTimeOffsetValue("sentDate", SentDate);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.ShipmentMethod>("shipmentMethod", ShipmentMethod);
            writer.WriteGuidValue("shipmentMethodId", ShipmentMethodId);
            writer.WriteObjectValue<global::AITGraph.Sdk.Models.PostalAddressType>("shippingPostalAddress", ShippingPostalAddress);
            writer.WriteStringValue("shipToContact", ShipToContact);
            writer.WriteStringValue("shipToName", ShipToName);
            writer.WriteStringValue("status", Status);
            writer.WriteDecimalValue("totalAmountExcludingTax", TotalAmountExcludingTax);
            writer.WriteDecimalValue("totalAmountIncludingTax", TotalAmountIncludingTax);
            writer.WriteDecimalValue("totalTaxAmount", TotalTaxAmount);
            writer.WriteDateValue("validUntilDate", ValidUntilDate);
        }
    }
}
#pragma warning restore CS0618
