// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    /// <summary>
    /// A security configuration task.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SecurityConfigurationTask : global::AITGraph.Sdk.Models.DeviceAppManagementTask, IParsable
    {
        /// <summary>The endpoint security configuration applicable platform.</summary>
        public global::AITGraph.Sdk.Models.EndpointSecurityConfigurationApplicablePlatform? ApplicablePlatform { get; set; }
        /// <summary>The endpoint security policy type.</summary>
        public global::AITGraph.Sdk.Models.EndpointSecurityConfigurationType? EndpointSecurityPolicy { get; set; }
        /// <summary>The endpoint security policy profile type.</summary>
        public global::AITGraph.Sdk.Models.EndpointSecurityConfigurationProfileType? EndpointSecurityPolicyProfile { get; set; }
        /// <summary>Information about the mitigation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Insights { get; set; }
#nullable restore
#else
        public string Insights { get; set; }
#endif
        /// <summary>The intended settings and their values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.KeyValuePair>? IntendedSettings { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.KeyValuePair> IntendedSettings { get; set; }
#endif
        /// <summary>The number of vulnerable devices. Valid values 0 to 65536</summary>
        public int? ManagedDeviceCount { get; set; }
        /// <summary>The vulnerable managed devices.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.VulnerableManagedDevice>? ManagedDevices { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.VulnerableManagedDevice> ManagedDevices { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AITGraph.Sdk.Models.SecurityConfigurationTask"/> and sets the default values.
        /// </summary>
        public SecurityConfigurationTask() : base()
        {
            OdataType = "#microsoft.graph.securityConfigurationTask";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.SecurityConfigurationTask"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::AITGraph.Sdk.Models.SecurityConfigurationTask CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AITGraph.Sdk.Models.SecurityConfigurationTask();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "applicablePlatform", n => { ApplicablePlatform = n.GetEnumValue<global::AITGraph.Sdk.Models.EndpointSecurityConfigurationApplicablePlatform>(); } },
                { "endpointSecurityPolicy", n => { EndpointSecurityPolicy = n.GetEnumValue<global::AITGraph.Sdk.Models.EndpointSecurityConfigurationType>(); } },
                { "endpointSecurityPolicyProfile", n => { EndpointSecurityPolicyProfile = n.GetEnumValue<global::AITGraph.Sdk.Models.EndpointSecurityConfigurationProfileType>(); } },
                { "insights", n => { Insights = n.GetStringValue(); } },
                { "intendedSettings", n => { IntendedSettings = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.KeyValuePair>(global::AITGraph.Sdk.Models.KeyValuePair.CreateFromDiscriminatorValue)?.AsList(); } },
                { "managedDeviceCount", n => { ManagedDeviceCount = n.GetIntValue(); } },
                { "managedDevices", n => { ManagedDevices = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.VulnerableManagedDevice>(global::AITGraph.Sdk.Models.VulnerableManagedDevice.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteEnumValue<global::AITGraph.Sdk.Models.EndpointSecurityConfigurationApplicablePlatform>("applicablePlatform", ApplicablePlatform);
            writer.WriteEnumValue<global::AITGraph.Sdk.Models.EndpointSecurityConfigurationType>("endpointSecurityPolicy", EndpointSecurityPolicy);
            writer.WriteEnumValue<global::AITGraph.Sdk.Models.EndpointSecurityConfigurationProfileType>("endpointSecurityPolicyProfile", EndpointSecurityPolicyProfile);
            writer.WriteStringValue("insights", Insights);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.KeyValuePair>("intendedSettings", IntendedSettings);
            writer.WriteIntValue("managedDeviceCount", ManagedDeviceCount);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.VulnerableManagedDevice>("managedDevices", ManagedDevices);
        }
    }
}
#pragma warning restore CS0618
