// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AITGraph.Sdk.Models
{
    /// <summary>
    /// Windows Domain Join device configuration.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WindowsDomainJoinConfiguration : global::AITGraph.Sdk.Models.DeviceConfiguration, IParsable
    {
        /// <summary>Active Directory domain name to join.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActiveDirectoryDomainName { get; set; }
#nullable restore
#else
        public string ActiveDirectoryDomainName { get; set; }
#endif
        /// <summary>Fixed prefix to be used for computer name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComputerNameStaticPrefix { get; set; }
#nullable restore
#else
        public string ComputerNameStaticPrefix { get; set; }
#endif
        /// <summary>Dynamically generated characters used as suffix for computer name. Valid values 3 to 14</summary>
        public int? ComputerNameSuffixRandomCharCount { get; set; }
        /// <summary>Reference to device configurations required for network connectivity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AITGraph.Sdk.Models.DeviceConfiguration>? NetworkAccessConfigurations { get; set; }
#nullable restore
#else
        public List<global::AITGraph.Sdk.Models.DeviceConfiguration> NetworkAccessConfigurations { get; set; }
#endif
        /// <summary>Organizational unit (OU) where the computer account will be created. If this parameter is NULL, the well known computer object container will be used as published in the domain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationalUnit { get; set; }
#nullable restore
#else
        public string OrganizationalUnit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AITGraph.Sdk.Models.WindowsDomainJoinConfiguration"/> and sets the default values.
        /// </summary>
        public WindowsDomainJoinConfiguration() : base()
        {
            OdataType = "#microsoft.graph.windowsDomainJoinConfiguration";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AITGraph.Sdk.Models.WindowsDomainJoinConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::AITGraph.Sdk.Models.WindowsDomainJoinConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AITGraph.Sdk.Models.WindowsDomainJoinConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "activeDirectoryDomainName", n => { ActiveDirectoryDomainName = n.GetStringValue(); } },
                { "computerNameStaticPrefix", n => { ComputerNameStaticPrefix = n.GetStringValue(); } },
                { "computerNameSuffixRandomCharCount", n => { ComputerNameSuffixRandomCharCount = n.GetIntValue(); } },
                { "networkAccessConfigurations", n => { NetworkAccessConfigurations = n.GetCollectionOfObjectValues<global::AITGraph.Sdk.Models.DeviceConfiguration>(global::AITGraph.Sdk.Models.DeviceConfiguration.CreateFromDiscriminatorValue)?.AsList(); } },
                { "organizationalUnit", n => { OrganizationalUnit = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("activeDirectoryDomainName", ActiveDirectoryDomainName);
            writer.WriteStringValue("computerNameStaticPrefix", ComputerNameStaticPrefix);
            writer.WriteIntValue("computerNameSuffixRandomCharCount", ComputerNameSuffixRandomCharCount);
            writer.WriteCollectionOfObjectValues<global::AITGraph.Sdk.Models.DeviceConfiguration>("networkAccessConfigurations", NetworkAccessConfigurations);
            writer.WriteStringValue("organizationalUnit", OrganizationalUnit);
        }
    }
}
#pragma warning restore CS0618
