// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AITGraph.Sdk.Models
{
    /// <summary>Flags representing which network profile types apply to a firewall rule.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WindowsFirewallRuleNetworkProfileTypes
    {
        /// <summary>No flags set.</summary>
        [EnumMember(Value = "notConfigured")]
        NotConfigured,
        /// <summary>The profile for networks that are connected to domains.</summary>
        [EnumMember(Value = "domain")]
        Domain,
        /// <summary>The profile for private networks.</summary>
        [EnumMember(Value = "private")]
        Private,
        /// <summary>The profile for public networks.</summary>
        [EnumMember(Value = "public")]
        Public,
    }
}
