// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CognitiveServices.Sdk.Entities
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public enum GetResponseFilterQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Entities")]
        #pragma warning disable CS1591
        Entities,
        #pragma warning restore CS1591
        [EnumMember(Value = "Places")]
        #pragma warning disable CS1591
        Places,
        #pragma warning restore CS1591
    }
}
